apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    version: blue  # initially point to the blue version
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer